### ISSUE TITLE
Performance issue in "Schedule" tab possibly related to "Task history" entries

### ISSUE THREAD

**Issue by ksdev-pl** [davidwernhart/AlDente#1639]
MacBook Pro M4
Aldente Pro 1.35.1

**To Reproduce**
- Have a lot of "Task history" entries
- Open "Schedule" tab in Automations
- After clicking on the tab the app freezes for few seconds before loading contents

**Expected Behavior**
- The tab opens quickly

**Additional context**
This issue might be called "Too many task history entries are generated / Task history list lag." You can see the issue in the screenshot:
<img width="1786" height="1444" alt="Image" src="https://github.com/user-attachments/assets/bb3f5295-9464-46a1-acd1-c6b588d91a46" />

I don't know how many history entries are there, but there are a lot of entries. I don't see an option to clear this list.

**Comment by MatthiasKerbl** [comment]
Hi @ksdev-pl,

Yes, this is most likely caused by the Task History. There was a bug in AlDente 1.35 that caused a lot of entries in the Task History. This bug is fixed in AlDente 1.35.1; however, the entries remain. To fix this, we will add a Clear History button in the next version.

Best,
Matthias

**Comment by ivansavra1** [comment]
I was about to report this, I get high CPU usage if I'm on the Schedule tab. Even if the window is not in focus, just leaving it in the background makes the app and menu bar icon unresponsive.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.36, which includes a fix for this issue. We have added a button to delete the Task History. To update to AlDente 1.36, open the Dashboard, click on the gear icon in the bottom left corner, and click on Check for Updates.
Please report back if it works for you.

Best,
Matthias

**Comment by ksdev-pl** [comment]
@MatthiasKerbl To be honest, it's a poor solution and will lead to the same issue in the future because it requires manual removal.

After I updated the app, I couldn't even click the removal button because the app froze on the Schedule screen. By the way, I managed to click "Clear All", thinking it was the new button, and cleared my scheduled task 🤦‍♂️ (The "Clear All Task History" option is not visible at the default window size, and you cannot increase the window because it's frozen...)

After force-killing the app, I'm sorry to say, but it doesn't work - I cannot click the new button because the window is frozen. I now cannot do anything on the "Schedule" screen.

**Comment by m3Lith** [comment]
I can confirm 1.36 does not solve the issue, and it seems even worse than before. Previously, I could open the Schedule menu and see the task history, even if it was laggy. With the current version, clicking on Schedule menu results in a blank window. Tried waiting for a few minutes, nothing appears.

<img width="754" height="672" alt="Image" src="https://github.com/user-attachments/assets/9935c4f0-30b8-4378-b1ec-3db4ad476966" />

@MatthiasKerbl, this still needs attention.

**Comment by ivansavra1** [comment]
1.36 has made this issue much worse for me, I can't use the UI after going to the Schedule area at least once. The whole program freezes, including the menu bar icon, and keeps using CPU time in the background unless I kill AlDente.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.36.1, which includes improvements for this issue. To update to AlDente 1.36.1, open the Dashboard, click on the gear icon in the bottom left corner, and click on Check for Updates.
Please report back if it is resolved for you.

Best,
Matthias

**Comment by m3Lith** [comment]
Can confirm that Schedule menu works normally with 1.36.1 for me. Task history is empty.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.37, which includes a fix for this issue. To update to AlDente 1.37, open the Dashboard, click on the gear icon in the bottom left corner, and click on Check for Updates.
Please report back if it works for you.

Best,
Matthias
