### ISSUE TITLE
Cyber Monday sale not working

### ISSUE THREAD

**Issue by vkplayz0** [davidwernhart/AlDente#1683]
Latest aldente version. brand new m4 macbook air 13 inch 24gb / 512gb / midnight. using safari on tahoe 26.1.

Says sale price is 17.49, upon clicking buy, it sets the price back to $25. even after entering details and attempting to confirm the payment it still appears to be charging $25.

<img width="805" height="728" alt="Image" src="https://github.com/user-attachments/assets/abf08dc3-3413-42a6-b94b-afca8425037c" />

https://apphousekitchen.com/aldente-overview/pricing/

**Comment by briankalid** [comment]
rt

**Comment by khkhk6562-png** [comment]
Same here. The banner says Cyber Monday Deal, but no discount is applied in the checkout.

**Comment by mail3dexter** [comment]
+1. I am facing same problem. How do we solve this before the sale goes off?

**Comment by LceAn** [comment]
This problem still exists at present

**Comment by altinsmaili** [comment]
+1

**Comment by Sergnnn** [comment]
Still exist.

**Comment by dxgsdp7z9h-ui** [comment]
I am having the same issue.  Please fix :).

**Comment by PinkyUni** [comment]
+1 Hope to see it fixed

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We are sorry for the inconvenience. This is fixed now.

Best,
Matthias

**Comment by LceAn** [comment]
> This problem still exists at present



> Hi everyone,
> 
> We are sorry for the inconvenience. This is fixed now.
> 
> Best, Matthias

Hello, I tried to use the discount payment option yesterday but couldn't get it to work. I tried again today and it's still showing the original price—it might have ended. Could you possibly provide me with a separate discount code?

**Comment by vkplayz0** [comment]
Bro the sale ended now, can you extend it due to this issue

**Comment by MatthiasKerbl** [comment]
Hi there,

Sorry for the inconvenience. The official sale is over, but with the discount code "CMGH2025" you can still get 30% off—only today.

Best,
Matthias
