### ISSUE TITLE
Active Discharge in Clamshell Mode is only available with the Pro version

### ISSUE THREAD

**Issue by Volodymyr-13** [davidwernhart/AlDente#805]
**Describe the bug**
Active Discharge in Clamshell Mode is only available with the Pro version - but I have PRO version.

**To Reproduce**
1. Update macOS with software update.
2. System restarts and after that I saw this error message.
3. Anyway discharge works a bit later.

**Expected behavior**
No any error messages, since I have a PRO version. 

**Screenshots**
<img width="260" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/197875104-58fba8d6-4d84-41c6-8a2b-e7dc56635596.png">

**MacBook (please complete the following information):**
 - MacBook 2021 M1
 - macOS version 13
 - AlDente Pro
 - AlDente Version 1.9.1
 - List of all enabled/disabled settings in AlDente:

<img width="432" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3391456/197875119-ee975134-7fe6-4adf-8611-63d2d5a617e9.png">
<img width="432" alt="Screenshot 2" src="https://user-images.githubusercontent.com/3391456/197875130-9cd4b2a3-7ab3-4188-91a4-46a02d282d29.png">

**Comment by Volodymyr-13** [comment]
Hmm, it's now actually showing me this each Mac restart, but then discharge works.

<img width="445" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/197886151-74ffb0bd-770c-4fd4-a9bb-ee7fb959af35.png">

Ventura 13.1

**Comment by MatthiasKerbl** [comment]
Hi @Volodymyr-13,

Thank you for pointing out this bug.
We could already find the cause of this issue and will fix it with the next update.

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @Volodymyr-13,

We have just released AlDente Pro 1.19.2 which has a fix for the bug you mentioned.

Cheers,
Matthias

**Comment by hossam-96** [comment]
The bug is still there for version 1.29, it happened after I used Migration Assistant to transfer my data to another Macbook.
I tried updating to 1.30 version, but it's still showing the message.

I don't have pro version, but discharging was working normally before.
